### ISSUE TITLE
Binance: error during transfer

### ISSUE THREAD

**Issue by ericfraselle** [cryptoeax/arbbot#146]
I received this error on binance branch:

17:36:05: BINANCE could give 1.77231898 GAS
17:36:05: POLONIEX is missing -1.77231898 GAS
17:36:05: Transfering 1.77231898 GAS BINANCE => POLONIEX
17:36:05: Depositaddress: <address>
PHP Notice:  Undefined variable: snurce in /var/www/arbbot/bot/CoinManager.php on line 854
PHP Fatal error:  Uncaught Error: Call to a member function withdraw() on null in /var/www/arbbot/bot/CoinManager.php:854
Stack trace:
#0 /var/www/arbbot/bot/CoinManager.php(899): CoinManager->doWithdraw(Object(Binance), 'GAS', '1.77231898', 'AG53RPbkRLwoEVe...')
#1 /var/www/arbbot/bot/CoinManager.php(406): CoinManager->withdraw(Object(Binance), Object(Poloniex), 'GAS', '1.77231898')
#2 /var/www/arbbot/bot/CoinManager.php(727): CoinManager->balance('GAS')
#3 /var/www/arbbot/bot/CoinManager.php(697): CoinManager->balanceAltcoins()
#4 /var/www/arbbot/bot/CoinManager.php(57): CoinManager->manageWallets(Object(Arbitrator))
#5 /var/www/arbbot/bot/Arbitrator.php(56): CoinManager->doManage(Object(Arbitrator))
#6 /var/www/arbbot/bot/Arbitrator.php(697): Arbitrator->loop()
#7 /var/www/arbbot/bot/Arbitrator.php(22): Arbitrator->innerRun()
#8 [internal function]: Arbitrator->{closure}(Object(React\EventLoop\Timer\Timer))
#9 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func(Object(Closure), Obje in /var/www/arbbot/bot/CoinManager.php on line 854

**Comment by ericfraselle** [comment]
Sorry, my fault, a typo when I try to debug.
