### ISSUE TITLE
database insertion error: Data too long for column 'coin' at row 1 - during management phase

### ISSUE THREAD

**Issue by Exalovic** [cryptoeax/arbbot#163]
I was having trouble with my database not recording things properly on bittrex so i wiped the mysql database,  then i started getting the following errors during the startup management

ERROR during management task: database insertion error: Data too long for column 'coin' at row 1
#0 /var/www/arbbot/bot/Database.php(187): Database::recordBalance()
#1 /var/www/arbbot/bot/CoinManager.php(224): Database::saveBalance()
#2 /var/www/arbbot/bot/CoinManager.php(694): CoinManager->saveSnapshot()
#3 /var/www/arbbot/bot/CoinManager.php(57): CoinManager->manageWallets()
#4 /var/www/arbbot/bot/Arbitrator.php(56): CoinManager->doManage()
#5 /var/www/arbbot/bot/Arbitrator.php(598): Arbitrator->loop()
#6 /var/www/arbbot/bot/Arbitrator.php(22): Arbitrator->innerRun()
#7 (): Closure$Arbitrator::__construct()
#8 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func()
#9 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#10 /var/www/arbbot/bot/Arbitrator.php(591): React\EventLoop\StreamSelectLoop->run()
#11 /var/www/arbbot/main.php(172): Arbitrator->run()
#12 {main}

**Comment by Exalovic** [comment]
Solved by reinstalling the bot
