### ISSUE TITLE
Issue in Bot

### ISSUE THREAD

**Issue by dinesh0311** [cryptoeax/arbbot#174]
The bot was running fine, but with out any changes it starts throwing this error. Do anyone else is facing any similar error ,

21:44:43: Error during main loop: API error response: Invalid Market
#0 /var/www/arbbot/bot/BittrexLikeExchange.php(283): BittrexLikeExchange->xtractResponse('{"success":fals...')
#1 /var/www/arbbot/bot/BittrexLikeExchange.php(96): BittrexLikeExchange->queryOrderbook('DOGE', 'BTC')
#2 /var/www/arbbot/bot/Exchange.php(167): BittrexLikeExchange->fetchOrderbook('DOGE', 'BTC')
#3 /var/www/arbbot/bot/Arbitrator.php(181): Exchange->getOrderbook('DOGE', 'BTC')
#4 /var/www/arbbot/bot/Arbitrator.php(116): Arbitrator->checkPairAt('DOGE_BTC', Object(Poloniex), Object(Bleutrade))
#5 /var/www/arbbot/bot/Arbitrator.php(92): Arbitrator->checkOpportunitiesAt(Object(Poloniex), Object(Bleutrade))
#6 /var/www/arbbot/bot/Arbitrator.php(59): Arbitrator->checkOpportunities()
#7 /var/www/arbbot/bot/Arbitrator.php(598): Arbitrator->loop()
#8 /var/www/arbbot/bot/Arbitrator.php(22): Arbitrator->innerRun()
#9 [internal function]: Arbitrator->{closure}(Object(React\EventLoop\Timer\Timer))

**Comment by ghost** [comment]
I am having the same issue did you ever find a solution?

**Comment by dinesh0311** [comment]
That issue was solved automatically after a couple of days for me !

**Comment by sparklestish** [comment]
Can you give me script that solves it?

**Comment by dinesh0311** [comment]
ah sorry! Currently I am not in access of the bot!
