### ISSUE TITLE
Could not get a REPLY 301 on BleuTrade (From Updated Installer Script PR)

### ISSUE THREAD

**Issue by ghost** [cryptoeax/arbbot#175]
Hello. I pulled from the installer script PR fork. It worked better than docker by a long shot.

I get this:

```
[23:17:34] Error during main loop: [BLEUTRADE] Could not get reply (HTTP 301): 
#0 /var/www/arbbot/bot/BittrexLikeExchange.php(283): Exchange->queryPublicJSON('https://bleutra...')
#1 /var/www/arbbot/bot/BittrexLikeExchange.php(96): BittrexLikeExchange->queryOrderbook('NEOS', 'BTC')
#2 /var/www/arbbot/bot/Exchange.php(167): BittrexLikeExchange->fetchOrderbook('NEOS', 'BTC')
#3 /var/www/arbbot/bot/Arbitrator.php(181): Exchange->getOrderbook('NEOS', 'BTC')
#4 /var/www/arbbot/bot/Arbitrator.php(116): Arbitrator->checkPairAt('NEOS_BTC', Object(Bittrex), Object(Bleutrade))
#5 /var/www/arbbot/bot/Arbitrator.php(91): Arbitrator->checkOpportunitiesAt(Object(Bittrex), Object(Bleutrade))
#6 /var/www/arbbot/bot/Arbitrator.php(59): Arbitrator->checkOpportunities()
#7 /var/www/arbbot/bot/Arbitrator.php(598): Arbitrator->loop()
#8 /var/www/arbbot/bot/Arbitrator.php(22): Arbitrator->innerRun()
#9 [internal function]: Arbitrator->{closure}(Object(React\EventLoop\Timer\Timer))
#10 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer))
#11 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#12 /var/www/arbbot/bot/Arbitrator.php(591): React\EventLoop\StreamSelectLoop->run()
#13 /var/www/arbbot/main.php(172): Arbitrator->run()
#14 {main}
[23:17:34] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:34] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:34] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:34] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:33] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:33] Checking NEOS_BTC at BITTREX -> BLEUTRADE...
[23:17:33] Checking 15 random pairs...
[23:17:33] Checking BITTREX vs BLEUTRADE (20 common pairs)
[23:17:33] Checking for opportunities...
[23:17:33] doManage()
[23:17:30] Refreshing wallets...
[23:17:29] Error during main loop: [BLEUTRADE] Could not get reply (HTTP 301): 
#0 /var/www/arbbot/bot/BittrexLikeExchange.php(283): Exchange->queryPublicJSON('https://bleutra...')
#1 /var/www/arbbot/bot/BittrexLikeExchange.php(96): BittrexLikeExchange->queryOrderbook('PPC', 'BTC')
#2 /var/www/arbbot/bot/Exchange.php(167): BittrexLikeExchange->fetchOrderbook('PPC', 'BTC')
#3 /var/www/arbbot/bot/Arbitrator.php(180): Exchange->getOrderbook('PPC', 'BTC')
#4 /var/www/arbbot/bot/Arbitrator.php(116): Arbitrator->checkPairAt('PPC_BTC', Object(Bleutrade), Object(Poloniex))
#5 /var/www/arbbot/bot/Arbitrator.php(91): Arbitrator->checkOpportunitiesAt(Object(Bleutrade), Object(Poloniex))
#6 /var/www/arbbot/bot/Arbitrator.php(59): Arbitrator->checkOpportunities()
#7 /var/www/arbbot/bot/Arbitrator.php(598): Arbitrator->loop()
#8 /var/www/arbbot/bot/Arbitrator.php(22): Arbitrator->innerRun()
#9 [internal function]: Arbitrator->{closure}(Object(React\EventLoop\Timer\Timer))
#10 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer))
#11 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#12 /var/www/arbbot/bot/Arbitrator.php(591): React\EventLoop\StreamSelectLoop->run()
#13 /var/www/arbbot/main.php(172): Arbitrator->run()
#14 {main}
[23:17:29] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:29] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:29] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:29] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:28] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:28] Checking PPC_BTC at BLEUTRADE -> POLONIEX...
[23:17:28] Checking 14 random pairs...
[23:17:28] Checking BLEUTRADE vs POLONIEX (14 common pairs)
[23:17:28] Checking for opportunities...
[23:17:28] doManage()
[23:17:25] Refreshing wallets...
[23:17:24] Error during main loop: [BLEUTRADE] Could not get reply (HTTP 301): 
#0 /var/www/arbbot/bot/BittrexLikeExchange.php(283): Exchange->queryPublicJSON('https://bleutra...')
#1 /var/www/arbbot/bot/BittrexLikeExchange.php(96): BittrexLikeExchange->queryOrderbook('BLK', 'BTC')
#2 /var/www/arbbot/bot/Exchange.php(167): BittrexLikeExchange->fetchOrderbook('BLK', 'BTC')
#3 /var/www/arbbot/bot/Arbitrator.php(180): Exchange->getOrderbook('BLK', 'BTC')
#4 /var/www/arbbot/bot/Arbitrator.php(116): Arbitrator->checkPairAt('BLK_BTC', Object(Bleutrade), Object(Poloniex))
#5 /var/www/arbbot/bot/Arbitrator.php(91): Arbitrator->checkOpportunitiesAt(Object(Bleutrade), Object(Poloniex))
#6 /var/www/arbbot/bot/Arbitrator.php(59): Arbitrator->checkOpportunities()
#7 /var/www/arbbot/bot/Arbitrator.php(598): Arbitrator->loop()
#8 /var/www/arbbot/bot/Arbitrator.php(22): Arbitrator->innerRun()
#9 [internal function]: Arbitrator->{closure}(Object(React\EventLoop\Timer\Timer))
#10 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer))
#11 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#12 /var/www/arbbot/bot/Arbitrator.php(591): React\EventLoop\StreamSelectLoop->run()
#13 /var/www/arbbot/main.php(172): Arbitrator->run()
#14 {main}
[23:17:24] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:24] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:24] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:24] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:23] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:23] Checking BLK_BTC at BLEUTRADE -> POLONIEX...
[23:17:23] Checking 14 random pairs...
[23:17:23] Checking BLEUTRADE vs POLONIEX (14 common pairs)
[23:17:23] Checking DOGE_BTC at POLONIEX -> BITTREX...
[23:17:23] Checking OMNI_BTC at POLONIEX -> BITTREX...
[23:17:22] Checking NEOS_BTC at POLONIEX -> BITTREX...
[23:17:19] Checking FCT_BTC at POLONIEX -> BITTREX...
[23:17:19] Checking PPC_BTC at POLONIEX -> BITTREX...
[23:17:16] Checking GNT_BTC at POLONIEX -> BITTREX...
[23:17:16] Checking VTC_BTC at POLONIEX -> BITTREX...
[23:17:16] Checking AMP_BTC at POLONIEX -> BITTREX...
[23:17:16] Checking OMG_BTC at POLONIEX -> BITTREX...
[23:17:15] Checking DGB_BTC at POLONIEX -> BITTREX...
[23:17:15] Checking CVC_BTC at POLONIEX -> BITTREX...
[23:17:15] SPREAD : 0.00002964 BTC = 0.00000000 BTC PROFIT
[23:17:14] Checking LTC_BTC at POLONIEX -> BITTREX...
[23:17:11] Checking FLO_BTC at POLONIEX -> BITTREX...
[23:17:11] Checking NXC_BTC at POLONIEX -> BITTREX...
[23:17:11] Checking NAV_BTC at POLONIEX -> BITTREX...
[23:17:11] Checking 15 random pairs...
[23:17:11] Checking POLONIEX vs BITTREX (29 common pairs)
[23:17:10] Checking OMG_BTC at BITTREX -> POLONIEX...
[23:17:10] Checking POT_BTC at BITTREX -> POLONIEX...
[23:17:10] Checking OMNI_BTC at BITTREX -> POLONIEX...
[23:17:10] Checking ZRX_BTC at BITTREX -> POLONIEX...
[23:17:09] Checking CVC_BTC at BITTREX -> POLONIEX...
[23:17:09] Checking AMP_BTC at BITTREX -> POLONIEX...
[23:17:09] Checking SYS_BTC at BITTREX -> POLONIEX...
[23:17:08] Checking VIA_BTC at BITTREX -> POLONIEX...
[23:17:08] Checking DOGE_BTC at BITTREX -> POLONIEX...
[23:17:07] Checking NXC_BTC at BITTREX -> POLONIEX...
[23:17:07] Checking PPC_BTC at BITTREX -> POLONIEX...
[23:17:07] Checking NEOS_BTC at BITTREX -> POLONIEX...
[23:17:06] Checking VTC_BTC at BITTREX -> POLONIEX...
[23:17:06] Checking STRAT_BTC at BITTREX -> POLONIEX...
[23:17:06] Checking ZEC_BTC at BITTREX -> POLONIEX...
[23:17:06] Checking 15 random pairs...
[23:17:06] Checking BITTREX vs POLONIEX (30 common pairs)
[23:17:06] Checking for opportunities...
[23:17:06] doManage()
[23:17:04] Refreshing wallets...
[23:17:03] Error during main loop: [BLEUTRADE] Could not get reply (HTTP 301): 
#0 /var/www/arbbot/bot/BittrexLikeExchange.php(283): Exchange->queryPublicJSON('https://bleutra...')
#1 /var/www/arbbot/bot/BittrexLikeExchange.php(96): BittrexLikeExchange->queryOrderbook('CLAM', 'BTC')
#2 /var/www/arbbot/bot/Exchange.php(167): BittrexLikeExchange->fetchOrderbook('CLAM', 'BTC')
#3 /var/www/arbbot/bot/Arbitrator.php(180): Exchange->getOrderbook('CLAM', 'BTC')
#4 /var/www/arbbot/bot/Arbitrator.php(116): Arbitrator->checkPairAt('CLAM_BTC', Object(Bleutrade), Object(Poloniex))
#5 /var/www/arbbot/bot/Arbitrator.php(91): Arbitrator->checkOpportunitiesAt(Object(Bleutrade), Object(Poloniex))
#6 /var/www/arbbot/bot/Arbitrator.php(59): Arbitrator->checkOpportunities()
#7 /var/www/arbbot/bot/Arbitrator.php(598): Arbitrator->loop()
#8 /var/www/arbbot/bot/Arbitrator.php(22): Arbitrator->innerRun()
#9 [internal function]: Arbitrator->{closure}(Object(React\EventLoop\Timer\Timer))
#10 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer))
#11 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#12 /var/www/arbbot/bot/Arbitrator.php(591): React\EventLoop\StreamSelectLoop->run()
#13 /var/www/arbbot/main.php(172): Arbitrator->run()
#14 {main}
[23:17:03] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:01] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:01] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:01] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:01] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:17:00] Checking CLAM_BTC at BLEUTRADE -> POLONIEX...
[23:17:00] Checking 14 random pairs...
[23:17:00] Checking BLEUTRADE vs POLONIEX (14 common pairs)
[23:17:00] Checking for opportunities...
[23:17:00] doManage()
[23:16:58] Refreshing wallets...
[23:16:57] Error during main loop: [BLEUTRADE] Could not get reply (HTTP 301): 
#0 /var/www/arbbot/bot/BittrexLikeExchange.php(283): Exchange->queryPublicJSON('https://bleutra...')
#1 /var/www/arbbot/bot/BittrexLikeExchange.php(96): BittrexLikeExchange->queryOrderbook('DOGE', 'BTC')
#2 /var/www/arbbot/bot/Exchange.php(167): BittrexLikeExchange->fetchOrderbook('DOGE', 'BTC')
#3 /var/www/arbbot/bot/Arbitrator.php(180): Exchange->getOrderbook('DOGE', 'BTC')
#4 /var/www/arbbot/bot/Arbitrator.php(116): Arbitrator->checkPairAt('DOGE_BTC', Object(Bleutrade), Object(Poloniex))
#5 /var/www/arbbot/bot/Arbitrator.php(91): Arbitrator->checkOpportunitiesAt(Object(Bleutrade), Object(Poloniex))
#6 /var/www/arbbot/bot/Arbitrator.php(59): Arbitrator->checkOpportunities()
#7 /var/www/arbbot/bot/Arbitrator.php(598): Arbitrator->loop()
#8 /var/www/arbbot/bot/Arbitrator.php(22): Arbitrator->innerRun()
#9 [internal function]: Arbitrator->{closure}(Object(React\EventLoop\Timer\Timer))
#10 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer))
#11 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#12 /var/www/arbbot/bot/Arbitrator.php(591): React\EventLoop\StreamSelectLoop->run()
#13 /var/www/arbbot/main.php(172): Arbitrator->run()
#14 {main}
[23:16:57] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:57] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:57] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:56] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:56] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:56] Checking DOGE_BTC at BLEUTRADE -> POLONIEX...
[23:16:56] Checking 14 random pairs...
[23:16:56] Checking BLEUTRADE vs POLONIEX (14 common pairs)
[23:16:56] Checking for opportunities...
[23:16:56] doManage()
[23:16:54] Refreshing wallets...
[23:16:53] Error during main loop: [BLEUTRADE] Could not get reply (HTTP 301): 
#0 /var/www/arbbot/bot/BittrexLikeExchange.php(283): Exchange->queryPublicJSON('https://bleutra...')
#1 /var/www/arbbot/bot/BittrexLikeExchange.php(96): BittrexLikeExchange->queryOrderbook('LTC', 'BTC')
#2 /var/www/arbbot/bot/Exchange.php(167): BittrexLikeExchange->fetchOrderbook('LTC', 'BTC')
#3 /var/www/arbbot/bot/Arbitrator.php(180): Exchange->getOrderbook('LTC', 'BTC')
#4 /var/www/arbbot/bot/Arbitrator.php(116): Arbitrator->checkPairAt('LTC_BTC', Object(Bleutrade), Object(Poloniex))
#5 /var/www/arbbot/bot/Arbitrator.php(91): Arbitrator->checkOpportunitiesAt(Object(Bleutrade), Object(Poloniex))
#6 /var/www/arbbot/bot/Arbitrator.php(59): Arbitrator->checkOpportunities()
#7 /var/www/arbbot/bot/Arbitrator.php(598): Arbitrator->loop()
#8 /var/www/arbbot/bot/Arbitrator.php(22): Arbitrator->innerRun()
#9 [internal function]: Arbitrator->{closure}(Object(React\EventLoop\Timer\Timer))
#10 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer))
#11 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#12 /var/www/arbbot/bot/Arbitrator.php(591): React\EventLoop\StreamSelectLoop->run()
#13 /var/www/arbbot/main.php(172): Arbitrator->run()
#14 {main}
[23:16:53] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:53] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:52] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:52] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:52] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:51] Checking LTC_BTC at BLEUTRADE -> POLONIEX...
[23:16:51] Checking 14 random pairs...
[23:16:51] Checking BLEUTRADE vs POLONIEX (14 common pairs)
[23:16:51] Checking for opportunities...
[23:16:51] doManage()
[23:16:49] Refreshing wallets...
[23:16:48] Error during main loop: [BLEUTRADE] Could not get reply (HTTP 301): 
#0 /var/www/arbbot/bot/BittrexLikeExchange.php(283): Exchange->queryPublicJSON('https://bleutra...')
#1 /var/www/arbbot/bot/BittrexLikeExchange.php(96): BittrexLikeExchange->queryOrderbook('BLK', 'BTC')
#2 /var/www/arbbot/bot/Exchange.php(167): BittrexLikeExchange->fetchOrderbook('BLK', 'BTC')
#3 /var/www/arbbot/bot/Arbitrator.php(180): Exchange->getOrderbook('BLK', 'BTC')
#4 /var/www/arbbot/bot/Arbitrator.php(116): Arbitrator->checkPairAt('BLK_BTC', Object(Bleutrade), Object(Poloniex))
#5 /var/www/arbbot/bot/Arbitrator.php(91): Arbitrator->checkOpportunitiesAt(Object(Bleutrade), Object(Poloniex))
#6 /var/www/arbbot/bot/Arbitrator.php(59): Arbitrator->checkOpportunities()
#7 /var/www/arbbot/bot/Arbitrator.php(598): Arbitrator->loop()
#8 /var/www/arbbot/bot/Arbitrator.php(22): Arbitrator->innerRun()
#9 [internal function]: Arbitrator->{closure}(Object(React\EventLoop\Timer\Timer))
#10 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer))
#11 /var/www/arbbot/lib/composer/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#12 /var/www/arbbot/bot/Arbitrator.php(591): React\EventLoop\StreamSelectLoop->run()
#13 /var/www/arbbot/main.php(172): Arbitrator->run()
#14 {main}
[23:16:48] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:48] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:48] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:47] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:47] [BLEUTRADE] Could not get reply (HTTP 301): 
[23:16:47] Checking BLK_BTC at BLEUTRADE -> POLONIEX...
[23:16:47] Checking 14 random pairs...
[23:16:47] Checking BLEUTRADE vs POLONIEX (14 common pairs)
[23:16:46] Checking NEOS_BTC at POLONIEX -> BITTREX...
[23:16:46] Checking NXC_BTC at POLONIEX -> BITTREX...
[23:16:46] Checking ZEC_BTC at POLONIEX -> BITTREX...
[23:16:45] Checking DGB_BTC at POLONIEX -> BITTREX...
[23:16:45] Checking FLO_BTC at POLONIEX -> BITTREX...
[23:16:45] Checking PPC_BTC at POLONIEX -> BITTREX...
[23:16:42] Checking FCT_BTC at POLONIEX -> BITTREX...
[23:16:41] Checking DCR_BTC at POLONIEX -> BITTREX...
[23:16:41] Checking AMP_BTC at POLONIEX -> BITTREX...
[23:16:41] Checking OMG_BTC at POLONIEX -> BITTREX...
[23:16:40] Checking CLAM_BTC at POLONIEX -> BITTREX...
[23:16:40] Checking CVC_BTC at POLONIEX -> BITTREX...
[23:16:40] Checking ZRX_BTC at POLONIEX -> BITTREX...
[23:16:37] Checking NAV_BTC at POLONIEX -> BITTREX...
[23:16:37] Checking BLK_BTC at POLONIEX -> BITTREX...
[23:16:37] Checking 15 random pairs...
[23:16:37] Checking POLONIEX vs BITTREX (29 common pairs)
[23:16:36] Checking CVC_BTC at BITTREX -> POLONIEX...
[23:16:36] Checking BLK_BTC at BITTREX -> POLONIEX...

```

**Comment by ghost** [comment]
If you could advise me of the logfile location, that would be amazing 👍

**Comment by dinesh0311** [comment]
The issue occurred with previous version also ! I am also facing the same error.

**Comment by dinesh0311** [comment]
Hi, did you find any solution for the above problem.
