### ISSUE TITLE
Problem with  length of the address withdrawal

### ISSUE THREAD

**Issue by Scorpic1** [cryptoeax/arbbot#33]
Hello All!

**cryptoeax** thank you for your work!

I am testing `pl-rewrite` branch now. I found one bug, i think this is due to the length of the address withdrawal

```
09:02:21: BITTREX: 10 SC (3 usages)
09:02:21: POLONIEX: 1600.42439517 SC (0 usages)
09:02:21: TOTAL: 1610.42439517 SC
09:02:21: AVERAGE: 1610.42439517 SC
09:02:21: XFER THRES.: 1000 SC
09:02:21: BITTREX is missing -1600.42439517 SC
09:02:21: POLONIEX could give 1600.42439517 SC
09:02:21: Transfering 1600.42439517 SC POLONIEX => BITTREX
09:02:22: Deposit address: 88918c50a572633c14a467bf89d489ba82a654663440db48e4672ea373674cf591c06b5c8aad
09:02:22: ERROR during management task: database insertion error: Data too long for column 'address' at row 1
#0 /var/www/arbitrage-bot/bot/CoinManager.php(761): Database::saveWithdrawal()
#1 /var/www/arbitrage-bot/bot/CoinManager.php(348): CoinManager->withdraw()
#2 /var/www/arbitrage-bot/bot/CoinManager.php(629): CoinManager->balance()
#3 /var/www/arbitrage-bot/bot/CoinManager.php(604): CoinManager->balanceAltcoins()
#4 /var/www/arbitrage-bot/bot/CoinManager.php(56): CoinManager->manageWallets()
#5 /var/www/arbitrage-bot/bot/Arbitrator.php(49): CoinManager->doManage()
#6 /var/www/arbitrage-bot/bot/Arbitrator.php(472): Arbitrator->loop()
#7 /var/www/arbitrage-bot/main.php(112): Arbitrator->run()
#8 {main}
09:02:22: Refreshing wallets...
```

Why bot send all SC coin to Bittrex account and bot do not write info xfers window.? Why not half of all SC coins?

**Comment by cryptoeax** [comment]
> Why bot send all SC coin to Bittrex account and bot do not write info xfers window.? Why not half of all SC coins?

I answered this part on the gitter channel.  The fix for the bug upcoming.
