### ISSUE TITLE
Not enough COIN error when transferring between exchanges

### ISSUE THREAD

**Issue by Scorpic1** [cryptoeax/arbbot#34]
With `pl-rewrite ` branch still have problem with re-balance coins to exchange like in #11 SC coin.
Now bot make transfer all coin SYS to other exchange. I did not know why bot did it.

I noticed this only after an error below:

```
21:13:24: Calculated P&L: -0.00000028
21:13:25: Transfering 23.54035660 SYS POLONIEX => BITTREX
21:13:25: Deposit address: SUz8D2kpDBYgY9xBGDZ2UbQUYFFWEBQErt
21:13:25: Error during main loop: [POLONIEX] API error response: Not enough SYS.
#0 /var/www/arbitrage-bot/bot/xchange/Poloniex.php(521): Poloniex->queryAPI()
#1 /var/www/arbitrage-bot/bot/xchange/Poloniex.php(64): Poloniex->queryWithdraw()
#2 /var/www/arbitrage-bot/bot/CoinManager.php(760): Poloniex->withdraw()
#3 /var/www/arbitrage-bot/bot/Arbitrator.php(387): CoinManager->withdraw()
#4 /var/www/arbitrage-bot/bot/Arbitrator.php(203): Arbitrator->trade()
#5 /var/www/arbitrage-bot/bot/Arbitrator.php(152): Arbitrator->checkAndTrade()
#6 /var/www/arbitrage-bot/bot/Arbitrator.php(142): Arbitrator->testOrderbooks()
#7 /var/www/arbitrage-bot/bot/Arbitrator.php(108): Arbitrator->checkPairAt()
#8 /var/www/arbitrage-bot/bot/Arbitrator.php(86): Arbitrator->checkOpportunitiesAt()
#9 /var/www/arbitrage-bot/bot/Arbitrator.php(55): Arbitrator->checkOpportunities()
#10 /var/www/arbitrage-bot/bot/Arbitrator.php(472): Arbitrator->loop()
#11 /var/www/arbitrage-bot/main.php(112): Arbitrator->run()
#12 {main}
21:13:26: Refreshing wallets...
```
Maybe problem in logic re-balance bot. Maybe problem in logic re-balance bot.

Why get this is error?
`21:13:25: Error during main loop: [POLONIEX] API error response: Not enough SYS.`

**Comment by Scorpic1** [comment]
I am confused

```
22:05:01: balance(SYS)
22:05:01:    BITTREX: 238.0347873 SYS (3 usages)
22:05:01:   POLONIEX: 23.48150571 SYS (2 usages)
22:05:01:       TOTAL: 261.51629301 SYS
22:05:01:     AVERAGE: 261.51629301 SYS
22:05:01: XFER THRES.: 1 SYS
22:05:02: BITTREX is missing -23.48150571 SYS
22:05:02: POLONIEX could give 23.48150571 SYS
22:05:02: Transfering 23.48150571 SYS POLONIEX => BITTREX
22:05:02: Deposit address: SUz8D2kpDBYgY9xBGDZ2UbQUYFFWEBQErt
```

**Comment by Scorpic1** [comment]
Again bot send all SYS coin and LBC coin to other exchange:

```
09:45:32: balanceAltcoins()
09:45:33: balance(SYS)
09:45:33:    BITTREX: 0.01 SYS (4 usages)
09:45:33:   POLONIEX: 260.85252728 SYS (2 usages)
09:45:33:       TOTAL: 260.86252728 SYS
09:45:33:     AVERAGE: 260.86252728 SYS
09:45:33: XFER THRES.: 1 SYS
09:45:33: BITTREX is missing -260.85252728 SYS
09:45:33: POLONIEX could give 260.85252728 SYS
09:45:34: Transfering 260.85252728 SYS POLONIEX => BITTREX
09:45:34: Deposit address: SUz8D2kpDBYgY9xBGDZ2UbQUYFFWEBQErt
09:45:34: balance(LBC)
09:45:35:    BITTREX: 0.02 LBC (3 usages)
09:45:35:   POLONIEX: 329.76485880 LBC (0 usages)
09:45:35:       TOTAL: 329.7848588 LBC
09:45:35:     AVERAGE: 329.78485880 LBC
09:45:35: XFER THRES.: 2 LBC
09:45:35: BITTREX is missing -329.76485880 LBC
09:45:35: POLONIEX could give 329.76485880 LBC
09:45:35: Transfering 329.76485880 LBC POLONIEX => BITTREX
09:45:35: Deposit address: bQnvBLynLkZXAA1VkcFeeGLc9QCPoTLEVs

```
**cryptoeax** Please check re-balance modul.

**Comment by cryptoeax** [comment]
I have already answered your question about rebalancing in https://gitter.im/cryptoeax-arbbot/Lobby?at=5a380fdb232e79134d656d6e.  I would appreciate if you read my answer there, you have repeated this question twice already.

Editing the issue summary to make it about the error in the first comment.

Do you know what the `SYS` balance on Poloniex was at the time of this transfer?  It's hard to do anything about this without knowing that.

I suspect that this error is fairly old based on the line numbers in the stack trace in the logged message.  I recently committed 25e6e959dec4847e8e20b56560f2c34484b9cbe9 which was intended to fix this issue in one case and the error you have pasted above has occurred before that.  Based on the logs in my own bot this error is still happening so there are some other corner cases that I have yet to discover but what needs to be done is to know the balance at the time this happens.  (Perhaps I need to add some logging...)

**Comment by Scorpic1** [comment]
**cryptoeax**, why bot transfer all coin like a SYS and LBC to other exchange? Before will be was half coins.

**Comment by cryptoeax** [comment]
Copy and pasting from the link I posted above:

the bot calculates the "need" for each exchange based on the history of the arbitrage opportunities it has observed before

if it has never seen any opportunity to sell SC on one of your exchanges, why would it hold any balance on that exchange? that would be a waste of your balance leverage, wouldn't it? 

It seems that you don't read what I keep telling you over and over again and keep repeating your question.  This is getting a bit frustrating.  If you're implying that you disagree with how the bot is designed, that is fine.  I am not planning to change how it's working.  If you want to change it, feel free to fork the project and make changes to the source code.

**Comment by Scorpic1** [comment]
Before if bot see 1600 SC coin on one account exchange, bot send other 800 SC coin to exchange. Now bot send all coin  SC ot other to exchange,i see it. i do not know why!

**Comment by cryptoeax** [comment]
This is the formula that computes the desired balance for each exchange: https://github.com/cryptoeax/arbbot/blob/38ec5108bc5df7645358e5629990480f457c864e/bot/CoinManager.php#L198

As you can see, the amount depends on the trade size and the average price so it will change *all the time*.  The bot is working exactly as designed.

**Comment by cryptoeax** [comment]
BTW if you are going to nit pick every single choice the bot makes, please take some time to study the source code.  After all you are trusting your money with this software, so try to get an understanding of how it works by reading the source code.  I'm not going to keep answering basic questions like this that can be answered by spending a few hours poking around.  The code is small and easy to ready if you're this interested.  With all due respect, I have limited time, and I prefer spending it on improving the bot rather than answer basic questions like this.  :-)

**Comment by cryptoeax** [comment]
The actual problem here isn't fixed at all.  I'm going to delete the off-topic comments to make things clearer.

**Comment by cryptoeax** [comment]
I suspect #39 may be the underlying bug that causes some of these errors to occur...
