### ISSUE TITLE
Warning: mysql_connect(): Lost connection to MySQL server at 'waiting for initial communication packet'

### ISSUE THREAD

**Issue by Scorpic1** [cryptoeax/arbbot#65]
Hello!

Get error below:

```
Warning: mysql_connect(): Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110 in /var/www/arbitrage-bot/bot/Database.php on line 18

Warning: mysql_error() expects parameter 1 to be resource, boolean given in /var/www/arbitrage-bot/bot/Database.php on line 20
11:12:47: Error during main loop: database error:
#0 /var/www/arbitrage-bot/bot/Database.php(363): Database::connect()
#1 /var/www/arbitrage-bot/bot/Exchange.php(43): Database::getAverageRate()
#2 /var/www/arbitrage-bot/bot/xchange/Bittrex.php(349): Exchange->calculateTradeablePairs()
#3 /var/www/arbitrage-bot/bot/Arbitrator.php(444): Bittrex->refreshExchangeData()
#4 /var/www/arbitrage-bot/bot/Arbitrator.php(43): Arbitrator->refreshCoinPairs()
#5 /var/www/arbitrage-bot/bot/Arbitrator.php(472): Arbitrator->loop()
#6 /var/www/arbitrage-bot/main.php(112): Arbitrator->run()
#7 {main}
11:12:48: Refreshing trading pairs...
```
What a error?

Thanks.

**Comment by cryptoeax** [comment]
The error message is very clear, your database server became unavailable for some reason.  This is unrelated to this software.  Please consult your server logs and look for help in mysql user forums.
